# Generated by Django 6.0.4 on 2026-06-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stagetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='stages',
            field=models.ManyToManyField(blank=True, to='core.stagetemplate'),
        ),
    ]
