# Generated by Django 6.0.4 on 2026-06-02 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_worker_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstage',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemstage',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_stages', to='core.worker'),
        ),
    ]
